datagovuk_find/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'pages#home'

  get "/sites/default/files/*organogram_path", to: redirect("https://s3-eu-west-1.amazonaws.com/datagovuk-#{Rails.env}-ckan-organogram/legacy/%{organogram_path}"), format: false

  if ENV["CKAN_REDIRECTION_URL"].present?
    get 'dataset/edit/:legacy_name', to: redirect(domain: ENV['CKAN_REDIRECTION_URL'], subdomain: '', path: "/dataset/edit/%{legacy_name}")
  end

  get 'dataset/:uuid', to: 'datasets#show', uuid: /[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}/

  scope module: 'legacy' do
    get 'dataset/:legacy_name',
        to: 'datasets#available_soon',
        constraints: ReferrerConstraint.new

    get 'dataset/:legacy_name',                                 to: 'datasets#redirect'
    get 'dataset/:legacy_dataset_name/resource/:datafile_uuid', to: 'datafiles#redirect'

    get 'data/search', to: 'search#redirect'
  end

  scope module: 'pages' do
    get 'about'
    get 'accessibility'
    get 'cookies'
    get 'dashboard'
    get 'privacy'
    get 'publishers'
    get 'site-changes', to: :site_changes
    get 'support'
    get 'terms'
  end

  match "404", to: "errors#not_found", via: :all
  match "500", to: "errors#internal_server_error", via: :all

  get 'search/', to: 'search#search'

  resources :tickets, only: %i[new create]
  get 'tickets/confirmation', to: 'tickets#confirmation'

  get 'data/map-preview', to: 'map_previews#show', as: 'map_preview'

  defaults format: :xml do
    get 'data/preview_proxy', to: 'map_previews#proxy'
    get 'data/preview_getinfo', to: 'map_previews#getinfo'
  end

  get 'dataset/:uuid/:name', to: 'datasets#show', as: 'dataset'
  get 'dataset/:dataset_uuid/:name/datafile/:datafile_uuid/preview', to: 'previews#show', as: 'datafile_preview'

  get 'acknowledge', to: 'messages#acknowledge'

  # Route everything else to CKAN
  if ENV["CKAN_REDIRECTION_URL"].present?
    match '*path',
      to: redirect(domain: ENV['CKAN_REDIRECTION_URL'], subdomain: '', path: "/%{path}"),
      via: :all,
      constraints: { path: /(?!#{Regexp.quote(Rails.application.config.assets.prefix[1..-1])}).+/ }
  end
end

datagovuk_find/app/models/dataset.rb
class Dataset
  include ActiveModel::Model
  include Elasticsearch::Model

  DatasetNotFound = Class.new(StandardError)

  attr_reader :name, :legacy_name, :title, :summary, :description, :foi_name,
              :organisation, :id, :uuid, :datafiles, :location1, :location2,
              :location3, :public_updated_at, :topic, :licence_custom, :docs,
              :contact_email, :foi_email, :foi_web, :inspire_dataset, :harvested,
              :contact_name, :released, :licence_title, :licence_url, :licence_code

  ORGANOGRAM_SCHEMA_IDS = [
    "538b857a-64ba-490e-8440-0e32094a28a7", # Local authority
    "d3c0b23f-6979-45e4-88ed-d2ab59b005d0", # Departmental
  ].freeze

  index_name ENV['ES_INDEX'] || "datasets-#{Rails.env}"

  def initialize(hash)
    @name = hash["name"]
    @legacy_name = hash["legacy_name"]
    @title = hash["title"]
    @summary = hash["summary"]
    @description = hash["description"]
    @id = hash["_id"]
    @uuid = hash["uuid"]
    @location1 = hash["location1"]
    @location2 = hash["location2"]
    @location3 = hash["location3"]
    @released = hash["released"]
    @licence = hash["licence"]
    @licence_other = hash["licence_other"]
    @licence_custom = hash["licence_custom"]
    @licence_title = hash["licence_title"]
    @licence_url = hash["licence_url"]
    @licence_code = hash["licence_code"]
    @public_updated_at = hash["public_updated_at"]
    @topic = hash["topic"]
    @contact_email = hash["contact_email"]
    @contact_name = hash["contact_name"]
    @foi_name = hash["foi_name"]
    @foi_email = hash["foi_email"]
    @foi_web = hash["foi_web"]
    @inspire_dataset = hash["inspire_dataset"]
    @harvested = hash["harvested"]
    @organisation = Organisation.new(hash["organisation"])
    @datafiles = hash["datafiles"].map { |file| Datafile.new(file) }
    @docs = hash["docs"].map { |file| Doc.new(file) }
    @schema_id = hash["schema_id"]
  end

  def self.get_by_query(query:)
    Dataset
      .search(query).to_a
      .map { |result| result._source.to_hash.merge(_id: result._id) }
      .reject { |attributes| attributes['title'].blank? }
      .map(&:stringify_keys)
      .map(&Dataset.method(:new))
  end

  def self.get_by_uuid(uuid:)
    get_by_query(query: Search::Query.by_uuid(uuid))
      .first || raise(DatasetNotFound)
  end

  def self.get_by_legacy_name(legacy_name:)
    get_by_query(query: Search::Query.by_legacy_name(legacy_name))
      .first || raise(DatasetNotFound)
  end

  def self.related(id)
    get_by_query(query: Search::Query.related(id))
  end

  def self.publishers
    query = { aggs: Search::Query.publishers_aggregation }
    buckets = Dataset.search(query).aggregations['organisations']['org_titles']['buckets']
    buckets.map { |bucket| bucket['key'] }.sort.uniq.reject(&:empty?)
  end

  def self.datafiles
    query = { aggs: Search::Query.datafiles_aggregation }
    Dataset.search(query).aggregations['datafiles']
  end

  def links
    docs + datafiles
  end

  def timeseries_datafiles
    datafiles.select(&:timeseries?)
  end

  def non_timeseries_datafiles
    datafiles.select(&:non_timeseries?)
  end

  def editable?
    harvested == false
  end

  def organogram?
    schema_id = @schema_id.gsub(/\["|"\]/, '')
    ORGANOGRAM_SCHEMA_IDS.include?(schema_id)
  end
end

datagovuk_find/app/controllers/datasets_controller.rb
class DatasetsController < ApplicationController
  include DatasetsHelper

  def show
    @dataset = Dataset.get_by_uuid(uuid: params[:uuid])
    @timeseries_datafiles = @dataset.timeseries_datafiles
    @non_timeseries_datafiles = @dataset.non_timeseries_datafiles
    @referer_query = referer_query
    @related_datasets = Dataset.related(@dataset.id)

    if request_to_outdated_url?
      return redirect_to newest_dataset_path, status: :moved_permanently
    end
  end

private

  def referer_query
    return if request.referer.nil?

    referer_query = URI(request.referer).query

    referer_query if current_host_matches_referer_host
  end

  def current_host_matches_referer_host
    URI(request.host).to_s == URI(request.referer).host.to_s
  end

  def request_to_outdated_url?
    request.path != newest_dataset_path
  end

  def newest_dataset_path
    dataset_path(@dataset.uuid, @dataset.name)
  end
end

datagovuk_find/app/controllers/legacy/datasets_controller.rb
class Legacy::DatasetsController < ApplicationController
  def redirect
    dataset = Dataset.get_by_legacy_name(legacy_name: params[:legacy_name])
    redirect_to dataset_path(dataset.uuid, dataset.name), status: :moved_permanently
  end
end

datagovuk_find/app/helpers/datasets_helper.rb
require 'uri'

module DatasetsHelper
  NO_MORE = {
      'discontinued' => 'Dataset no longer updated',
      'never' => 'No future updates',
      'one off' => 'No future updates',
      'default' => 'Not available'
  }.freeze

  def to_markdown(content)
    markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML, autolink: true, tables: false)
    markdown.render(content).html_safe
  end

  def unescape(str)
    str = strip_tags(str).html_safe
    str = str.gsub(/&(amp;)+/, '&')
    HTMLEntities.new.decode(str)
  end

  def dataset_location(dataset)
    locations(dataset).empty? ? NO_MORE['default'] : locations(dataset)
  end

  def expected_location_class_for(dataset)
    "dgu-secondary-text" if locations(dataset).empty?
  end

  def input_box_class_for(ticket, field)
    if ticket.errors[field].any?
      "form-control form-control-2-3 form-control-error"
    else
      "form-control form-control-2-3"
    end
  end

  def shorten_title(title)
    title.truncate(70, separator: ' ', omission: ' ...')
  end

  def to_json_ld(dataset)
    dataset_metadata = {
      "@context": "http://schema.org",
      "@type": "Dataset",
      name: dataset.title,
      url: "#{request.protocol}#{request.host_with_port}#{request.fullpath}",
      includedInDataCatalog: {
        "@type": "DataCatalog",
        url: "#{request.protocol}#{request.host_with_port}"
      },
      creator: {
        "@type": "Organization",
        name: dataset.organisation.title
      },
      description: dataset.summary,
      license: {
        "@type": "CreativeWork",
        name: dataset.licence_title,
        text: dataset.licence_custom,
        url: dataset.licence_url
      },
      dateModified: dataset.public_updated_at
    }
    if dataset.topic
      dataset_metadata[:keywords] = dataset.topic['title']
    end
    files = metadata_files(dataset)
    unless files.empty?
      dataset_metadata[:distribution] = files
    end
    dataset_metadata.to_json
  end

  def metadata_files(dataset)
    files = []
    dataset.datafiles.each do |file|
      files.push(
        "@type": 'DataDownload',
        contentUrl: file.url,
        fileFormat: file.format,
        name: file.name
      )
    end
    files
  end

  def contact_information_exists?(dataset)
    contact_email_exists?(dataset) || foi_details_exist?(dataset)
  end

  def contact_email_exists?(dataset)
    contact_email_for(dataset).present?
  end

  def contact_name_for(dataset)
    dataset.contact_name.presence || dataset.organisation.contact_name
  end

  def contact_email_is_email?(dataset)
    contact_email_for(dataset) =~ /@/
  end

  def contact_email_for(dataset)
    dataset.contact_email.presence || dataset.organisation.contact_email
  end

  def foi_details_exist?(dataset)
    foi_email_exists?(dataset) || foi_web_address_exists?(dataset)
  end

  def foi_email_exists?(dataset)
    foi_email_for(dataset).present?
  end

  def foi_web_address_exists?(dataset)
    foi_web_address_for(dataset).present?
  end

  def foi_name_for(dataset)
    dataset.foi_name.presence || dataset.organisation.foi_name
  end

  def foi_email_for(dataset)
    dataset.foi_email.presence || dataset.organisation.foi_email
  end

  def foi_web_address_for(dataset)
    (dataset.foi_web.presence || dataset.organisation.foi_web).to_s
  end

private

  def locations(dataset)
    %w[location1 location2 location3]
        .map { |loc| dataset.send(loc) }
        .join(" ")
        .strip
  end

  def most_recent_datafile(dataset)
    dataset.datafiles.max_by(&:created_at)
  end
end

datagovuk_find/app/views/datasets/_additional_info.html.erb
  <section class="dgu-additional-info">
    <h2 class="heading-medium">
      <%= t('.additional_info') %>
    </h2>
    <% if dataset.description.present? %>
      <p class="dgu-additional-info__notes">
        <%= dataset.description %>
      </p>
    <% end %>

    <% if dataset.inspire_dataset.present? %>
      <% i = dataset.inspire_dataset %>

      <details>
        <% unless browser.ie? || browser.edge? %>
          <summary><span class="summary"><%= t('.view_additional_metadata') %></span></summary>
        <% end %>


        <div class="panel panel-border-narrow">

          <dl class="dgu-deflist">
            <% if i['metadata_date'] %>
              <dt><%= t('.inspire_added') %></dt>
              <dd><%= i['metadata_date'] %></dd>
            <% end %>
            <% if i['access_constraints'] %>
              <% ref = JSON.parse(i['access_constraints']) %>
              <dt><%= t('.inspire_access_constraints') %></dt>
              <dd><%= ref.first || t('.inspire_access_constraints_unspecified') %></dd>
            <% end %>
            <% if i['guid'] %>
              <dt><%= t('.inspire_guid') %></dt>
              <dd><%= i['guid'] %></dd>
            <% end %>
            <% if i['bbox_east_long'] and i['bbox_west_long'] and i['bbox_north_lat'] and i['bbox_south_lat'] %>
              <dt><%= t('.inspire_extent') %></dt>
              <dd>
                <%= t('.inspire_latitude') %>: <%= i['bbox_north_lat'] %>° <%= t('.inspire_to') %> <%= i['bbox_south_lat'] %>°</dd>
              <dd>
                <%= t('.inspire_longitude') %>: <%= i['bbox_west_long'] %>° <%= t('.inspire_to') %> <%= i['bbox_east_long'] %>°
              </dd>
            <% end %>
            <% if i['spatial_reference_system'] %>
              <dt><%= t('.inspire_spatial_ref_system') %></dt>
              <dd><%= i['spatial_reference_system'] %></dd>
            <% end %>
            <% if i['dataset_reference_date'] %>
              <% ref = JSON.parse(i['dataset_reference_date']) %>
              <dt><%= t('.inspire_dataset_ref_date') %></dt>
              <% ref.each do |date| %>
                <dd><%= date['value'] %> (<%= date['type'] %>)</dd>
              <% end %>
            <% end %>
            <% if i['frequency_of_update'] %>
              <dt><%= t('.inspire_frequency') %></dt>
              <dd><%= i['frequency_of_update'] %></dd>
            <% end %>
            <% if i['responsible_party'] %>
              <dt><%= t('.inspire_responsible_party') %></dt>
              <dd><%= i['responsible_party'] %></dd>
            <% end %>
            <% if i['resource_type'] %>
              <dt><%= t('.inspire_iso_resource') %></dt>
              <dd><%= i['resource_type'] %></dd>
            <% end %>
            <% if i['metadata_language'] %>
              <dt><%= t('.inspire_metadata_lang') %></dt>
              <dd><%= i['metadata_language'] %></dd>
            <% end %>
            <% if i['harvest_object_id'] %>
              <dt><%= t('.inspire_gemini_record') %></dt>
              <dd>
                <%= link_to t('.xml'), "/api/2/rest/harvestobject/#{ i['harvest_object_id'] }/xml" %>
                <br />
                <%= link_to t('.html'), "/api/2/rest/harvestobject/#{ i['harvest_object_id'] }/html" %>
              </dd>
            <% end %>
          </dl>
        </div>
      </details>
    <% end %>
  </section>

datagovuk_find/app/views/datasets/_breadcrumb.html.erb
<% if @dataset %>
  <div class="grid-row">
    <!-- Only display breadcrumb if the referrer host matches the application host  -->
    <div class="column-full">
      <div class="breadcrumbs">
        <nav aria-label="Breadcrumb">
          <ol>
            <li>
              <%= link_to t('.home'), root_path %>
            </li>
            <li>
              <% if @referer_query.nil? %>
                <%= @dataset.organisation.title %>
              <% else %>
                <%= link_to t('.search'), "/search?#{@referrer}" %>
              <% end %>
            </li>
            <li aria-current="page">
              <%= shorten_title(@dataset.title) %>
            </li>
          </ol>
        </nav>
      </div>
    </div>
  </div>
<% end %>

datagovuk_find/app/views/datasets/_contact.html.erb
<%
  if contact_email_is_email?(dataset)
    mail = mail_to(contact_email_for(dataset), nil, {'data-ga-event': 'contact', 'data-ga-publisher': @dataset.organisation.name})
  else
    mail = link_to(contact_email_for(dataset), contact_email_for(dataset), {'data-ga-event': 'contact', 'data-ga-publisher': @dataset.organisation.name})
  end
%>
<section class="contact">
  <h2 class="heading-medium">
    <%= t('datasets.contact.contact') %>
  </h2>

  <% if contact_email_exists?(dataset) %>
    <div class="column-one-half enquiries">
      <h3 class="heading-small">
        <%= t('datasets.contact.enquiries') %>
      </h3>
      <p>
        <%= content_tag(:span, contact_name_for(dataset)) if contact_name_for(dataset).present? %>
        <%= content_tag(:span, mail) if mail.present? %>
      </p>
    </div>
  <% end %>

  <% if foi_details_exist?(dataset) %>
    <div class="column-one-half foi">
      <h3 class="heading-small">
        <%= t('datasets.contact.foi_requests') %>
      </h3>

      <p>
        <%= content_tag(:span, foi_name_for(dataset)) if foi_name_for(dataset).present? %>
        <%= content_tag(:span, mail_to(foi_email_for(dataset), nil, {class: 'ga-contact'})) if foi_email_for(dataset).present? %>
        <% if foi_web_address_for(dataset).present? %>
          <%= content_tag(:span) do %>
            <%= link_to(foi_web_address_for(dataset), foi_web_address_for(dataset), { class: 'ga-contact'} ) %>
          <% end %>
        <% end %>

      </p>
    </div>
  <% end %>
</section>

datagovuk_find/app/views/datasets/_datafile_table.html.erb
<table class="dgu-datafiles">
  <tr>
    <th class="title small"><%= t('.link_to_data') %></th>
    <th><%= t('.format') %></th>
    <th><%= t('.file_added') %></th>
    <th><%= t('.data_preview') %></th>
  </tr>
  <tbody>
    <% sort_by_created_at(datafiles).each_with_index do |datafile, index| %>
      <tr class="<%= show_more?(index) %> dgu-datafile">
        <td class="title small">
          <%= link_to datafile.url,
              :data => {
                'ga-event' => "download",
                'ga-format' => "CSV",
                'ga-publisher' => @dataset.organisation.name
              },
              'aria-label': "Download datafile #{datafile.name} format: #{format_of(datafile)} dataset: #{@dataset.title}" do %>
            <%= (datafile.name ? datafile.name : 'Data Link') %>
            <span class='visually-hidden'>Download datafile '<%= datafile.name %>', Format: <%= format_of(datafile) %>, Dataset: <%= @dataset.title %></span>
          <% end %>
        </td>
        <% if datafile.format.blank? %>
          <td class="dgu-secondary-text">N/A</td>
        <% else %>
          <td><%= datafile.format.upcase %>
          <% if datafile.size %>
            (<%= datafile.size.number_to_human_size %> )
          <% end %>
          </td>
        <% end %>
        <% if datafile.created_at.present? %>
          <td>
            <%= format_timestamp(datafile.created_at) %>
          </td>
        <% else %>
          <td class="dgu-secondary-text">Not available</td>
        <% end %>
        <td class="datafiles__preview">
          <% if datafile.html? %>
            <%= link_to t('.go_to_site'), datafile.url %>
          <% elsif datafile.csv? %>
            <%= link_to t('.preview'),
                datafile_preview_path(@dataset.uuid, @dataset.name, datafile.uuid),
                :data => {
                  :'ga-event' => 'preview',
                  :'ga-format' => (datafile.format.presence || 'n/a').upcase,
                  :'ga-publisher' => @dataset.organisation.name
                  }
            %>
          <% elsif datafile.wms? && @dataset.inspire_dataset.present? %>
            <%= link_to t('.map_preview'), map_preview_url(@dataset, datafile) %>
          <% else %>
            <span class="dgu-secondary-text"><%= t('.not_available') %></span>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<% if datafiles.length > 5 && !browser.ie?(version: 8) %>
  <button class="button secondary show-toggle" aria-label="Show more data links">Show more</button>
<% end %>

datagovuk_find/app/views/datasets/_meta_data.html.erb
<% content_for :head do %>
  <%= tag.meta name: 'dc:title',   content: unescape(@dataset.title) %>
  <%= tag.meta name: 'dc:creator', content: @dataset.organisation.title %>
  <%= tag.meta name: 'dc:date',    content: Date.parse(@dataset.public_updated_at).to_formatted_s %>

  <% if @dataset.licence_title.present? %>
    <%= tag.meta name: 'dc:rights', content: @dataset.licence_title %>
  <% end %>
<% end %>

<section class="meta-data">
  <div class="grid-row">
    <div class="column-two-thirds">
      <h1 class="heading-large" property="dc:title">
        <%= unescape(@dataset.title) %>
      </h1>
    </div>
  </div>

  <div class="grid-row">
    <div class="column-two-thirds">
      <div class="dgu-metadata__box dgu-metadata__box--in-dataset">
        <dl class="metadata">
          <% unless @dataset.released %>
            <dt><%= t('.availability') %>:</dt>
            <dd>
              <span class="dgu-highlight">Not released</span>
            </dd>
          <% end %>
          <dt><%= t('.published_by') %>:</dt>

          <dd property="dc:creator">
            <%= @dataset.organisation.title %>
          </dd>

          <dt><%= t('.last_updated') %>:</dt>
          <dd property="dc:date" content="<%= format_timestamp(@dataset.public_updated_at) %>">
            <%= format_timestamp(@dataset.public_updated_at) %>
          </dd>

          <dt><%= t('.topic') %>:</dt>
          <% if @dataset.topic %>
            <dd><%= @dataset.topic['title'] %></dd>
          <% else %>
            <dd><%= t('.topic_not_added') %></dd>
          <% end %>

          <dt><%= t('.licence') %>:</dt>
          <dd property="dc:rights">
            <% if @dataset.licence_url.present? %>
              <%= link_to @dataset.licence_title,
                          @dataset.licence_url,
                          rel: 'dc:rights' %>
            <% elsif @dataset.licence_title.present? %>
              <%= @dataset.licence_title %>
            <% elsif @dataset.licence_custom.present? %>
              <%= t('.other_licence') %>
            <% else %>
              <%= t('.no_licence') %>
            <% end %>

            <% if @dataset.licence_custom.present? %>
              <br>
              <%= link_to t('.view_licence_information'),
                            '#licence-info' %>
            <% end %>
          </dd>
        </dl>

        <h3 class="heading-small">
          <%= t('.summary') %>
        </h3>
        <div class="js-summary" style="line-height: 1.5em; overflow: hidden" property="dc:description">
          <%= to_markdown(@dataset.summary) %>
        </div>
      </div>
    </div>

    <div class="column-one-third dgu-dataset-right">
      <div class="dgu-dataset-right__sidebar__publisher_datasets">
        <h3 class="heading-small"><%= t('.publisher_datasets') %></h3>
        <%= link_to search_path(filters: { publisher: @dataset.organisation.title }) do %>
          <%= "All datasets from #{@dataset.organisation.title}" %>
        <% end %>
      </div>

      <% unless @related_datasets.empty? %>
        <div class="dgu-dataset-right__sidebar">
          <h3 class="heading-small"><%= t('.related_datasets') %></h3>
          <ul>
            <% @related_datasets.each do |dataset| %>
              <li>
                <%= link_to unescape(dataset.title), dataset_path(dataset.uuid, dataset.name) %>
              </li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <h3 class="heading-small"><%= t('.search_gov_data') %></h3>
      <form action="/search" method="GET" class="dgu-search-box">
        <label for="q" class="visuallyhidden"><%= t('.accessibility.search_box_label') %></label>
        <input id="q"
               name="q"
               type="text"
               class="form-control dgu-search-box__input"/><button type="submit"
                                                                   class="dgu-search-box__button">
                                                            <%= t('.accessibility.search_box_button')%>
                                                           </button>
      </form>
    </div>
  </div>
</section>

datagovuk_find/app/views/datasets/_no_datafiles.html.erb
<div class="panel panel-border-narrow">
  <p><%= t('datasets.show.not_released') %><br />
  <% if contact_information_exists?(dataset) %>
    <%= t('datasets.show.contact_the_publisher') %>
  <% else %>
    <%= t('datasets.show.contact_the_team') %>
    <%= link_to 'data.gov.uk/support', support_path %>
    <%= t('datasets.show.if_you_have_questions') %>
  <% end %>
</div>

datagovuk_find/app/views/datasets/_non_timeseries_data.html.erb
<%= render partial: 'datafile_table', locals: { datafiles: datafiles } %>

datagovuk_find/app/views/datasets/_supporting_docs.html.erb
<section class="supporting docs">
  <h2 class="heading-medium">
    <%= t('.supporting_docs')%>
  </h2>

  <table>
    <thead>
    <tr>
      <th class="title"><%= t('.link_to_doc')%></th>
      <th><%= t('.format')%></th>
      <th><%= t('.date_added')%></th>
    </tr>
    </thead>
    <tbody>
    <% dataset.docs.each do |doc| %>
      <tr>
        <td class="title">
          <a href="<%= doc.url%>"><%= doc.name %></a>
        </td>
        <td><%= doc.format or "N/A" %></td>
        <td><%= format_timestamp(doc.created_at) or "N/A" %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
</section>

datagovuk_find/app/views/datasets/_timeseries_data.html.erb
<% if browser.ie?(8) %>
  <ul>
    <% group_and_order(datafiles).each do |year, datafiles| %>
      <li>
        <div>
          <h3 class="heading-small">
            <%= year.presence || "Other data files" %>
          </h3>
        </div>
        <%= render partial: 'datafile_table', locals: { datafiles: datafiles } %>
      <% end %>
      </li>
  </ul>
<% else %>
  <ul>
    <% group_and_order(datafiles).each do |year, datafiles| %>
      <li class="showHide">
        <div class="year-expand showHide-control">
          <h3 class="heading-small">
            <button class="dgu-datafiles__year button secondary">
              <%= year.presence || "Other data files" %>
            </button>
          </h3>
          <div>
            <button class="dgu-datafiles__expand js-expand button secondary">+</button>
          </div>
        </div>
        <div class="showHide-content" style="display:none">
          <%= render partial: 'datafile_table', locals: { datafiles: datafiles } %>
        </div>
      <% end %>
      </li>
  </ul>
<% end %>

datagovuk_find/app/views/datasets/show.html.erb
<% content_for :page_title do %><%= @dataset.title %><% end %>

<script type="application/ld+json">
 <%= raw to_json_ld(@dataset) %>
</script>

<%= content_for :breadcrumb do %>
  <%= render 'breadcrumb' %>
<% end%>

<main role="main" id="content">
  <div>
    <%= render "meta_data" %>

    <div class="grid-row">
      <div class="column-full">
        <section class="dgu-datalinks">
          <h2 class="heading-medium"><%= t('.data_links')%>
          <% unless @timeseries_datafiles.empty? %>
            <!-- accordions for time series datasets -->
            <% if !browser.ie?(8) %>
              <span class="showHide-open-all"><%= t('.open_all') %></span>
            <% end %>
          <% end %>
          </h2>

          <% unless @timeseries_datafiles.empty? %>
            <%= render partial: "timeseries_data", locals: { datafiles: @timeseries_datafiles } %>
          <% end %>

          <% unless @non_timeseries_datafiles.empty? %>
            <%= render partial: "non_timeseries_data", locals: { datafiles: @non_timeseries_datafiles } %>
          <% end %>

          <% if @dataset.datafiles.empty? %>
            <%= render partial: "no_datafiles", locals: { dataset: @dataset } %>
          <% end %>

        </section>
      </div>
    </div>

    <% if @dataset.description.present? || @dataset.inspire_dataset.present? %>
      <%= render partial: "additional_info", locals: { dataset: @dataset } %>
    <% end %>

    <% unless @dataset.docs.empty? %>
      <%= render partial: "supporting_docs", locals: { dataset: @dataset } %>
    <% end %>

    <% if contact_information_exists?(@dataset) %>
      <%= render partial: "contact", locals: { dataset: @dataset } %>
    <% end %>

    <% if @dataset.licence_custom.present? %>
      <section class="dgu-licence-info">
        <div class="grid-row">
          <div class="column-full">
            <h2 class="heading-medium" id="licence-info">
              <%= t('.licence_information') %>
            </h2>
            <p class="dgu-licence-info__notes">
              <%= to_markdown(@dataset.licence_custom) %>
            </p>
          </div>
        </div>
      </section>
    <% end %>

    <% if @dataset.editable? %>
      <section>
        <div class="grid-row">
          <div class="column-full">
            <h2 class="heading-medium"><%= t('datasets.publishers.title') %></h2>
            <div role="note" aria-label="Publisher information" class="panel panel-border-narrow text">
              <p><%= t('datasets.publishers.information') %></p>
            </div>
            <p><%= link_to t('datasets.publishers.button'), "/dataset/edit/#{@dataset.legacy_name}", role: 'button', class: 'button', rel: %w(nofollow) %></p>
          </div>
        </div>
      </section>
    <% end %>

  </div>
</main>