datagovuk_find/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'pages#home'

  get "/sites/default/files/*organogram_path", to: redirect("https://s3-eu-west-1.amazonaws.com/datagovuk-#{Rails.env}-ckan-organogram/legacy/%{organogram_path}"), format: false

  if ENV["CKAN_REDIRECTION_URL"].present?
    get 'dataset/edit/:legacy_name', to: redirect(domain: ENV['CKAN_REDIRECTION_URL'], subdomain: '', path: "/dataset/edit/%{legacy_name}")
  end

  get 'dataset/:uuid', to: 'datasets#show', uuid: /[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}/

  scope module: 'legacy' do
    get 'dataset/:legacy_name',
        to: 'datasets#available_soon',
        constraints: ReferrerConstraint.new

    get 'dataset/:legacy_name',                                 to: 'datasets#redirect'
    get 'dataset/:legacy_dataset_name/resource/:datafile_uuid', to: 'datafiles#redirect'

    get 'data/search', to: 'search#redirect'
  end

  scope module: 'pages' do
    get 'about'
    get 'accessibility'
    get 'cookies'
    get 'dashboard'
    get 'privacy'
    get 'publishers'
    get 'site-changes', to: :site_changes
    get 'support'
    get 'terms'
  end

  match "404", to: "errors#not_found", via: :all
  match "500", to: "errors#internal_server_error", via: :all

  get 'search/', to: 'search#search'

  resources :tickets, only: %i[new create]
  get 'tickets/confirmation', to: 'tickets#confirmation'

  get 'data/map-preview', to: 'map_previews#show', as: 'map_preview'

  defaults format: :xml do
    get 'data/preview_proxy', to: 'map_previews#proxy'
    get 'data/preview_getinfo', to: 'map_previews#getinfo'
  end

  get 'dataset/:uuid/:name', to: 'datasets#show', as: 'dataset'
  get 'dataset/:dataset_uuid/:name/datafile/:datafile_uuid/preview', to: 'previews#show', as: 'datafile_preview'

  get 'acknowledge', to: 'messages#acknowledge'

  # Route everything else to CKAN
  if ENV["CKAN_REDIRECTION_URL"].present?
    match '*path',
      to: redirect(domain: ENV['CKAN_REDIRECTION_URL'], subdomain: '', path: "/%{path}"),
      via: :all,
      constraints: { path: /(?!#{Regexp.quote(Rails.application.config.assets.prefix[1..-1])}).+/ }
  end
end

datagovuk_find/app/views/layouts/_analytics.html.erb
<% if Rails.application.config.analytics_tracking_id.present? %>
  <%= javascript_tag do %>
   (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
     (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
                            m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
   })(window,document,'script','https://www.google-analytics.com/analytics.js','ga')

   ga('create', '<%= Rails.application.config.analytics_tracking_id %>', 'auto')
   var dimensions = {}

   $(document).ready(function() {
     dimensions['dimension11'] = 'find-open-data'
     ga('send', 'pageview', dimensions)
     $('[data-ga-event]').on('click', sendAnalyticsEvent)
   })

   // Analytics event firing
   function sendAnalyticsEvent() {
     var eventType = $(this).data('ga-event')
     var orgName = $(this).data('ga-publisher')
     var eventParams = {}
     switch (eventType) {
       case 'download':
         eventParams = {
           hitType: 'event',
           eventCategory: 'datafile',
           eventAction: 'download',
           eventLabel: $(this).attr('href'),
           dimension4: orgName,
           dimension5: $(this).data('ga-format'),
           dimension11: 'find-open-data'
         }
         break
       case 'contact':
         eventParams = {
           hitType: 'event',
           eventCategory: 'contact-details',
           eventAction: 'click',
           eventLabel: orgName,
           dimension4: orgName,
           dimension11: 'find-open-data'
         }
         break
       case 'preview':
         eventParams = {
           hitType: 'event',
           eventCategory: 'datafile-preview',
           eventAction: 'click',
           eventLabel: $(this).attr('href'),
           dimension4: orgName,
           dimension5: $(this).data('ga-format'),
           dimension11: 'find-open-data'
         }
         break
       case 'preview-download':
         eventParams = {
           hitType: 'event',
           eventCategory: 'datafile-preview',
           eventAction: 'download',
           eventLabel: $(this).attr('href'),
           dimension4: orgName,
           dimension5: $(this).data('ga-format'),
           dimension11: 'find-open-data'
         }
         break
     }
     ga('send', eventParams)
   }
  <% end %>
<% end %>

datagovuk_find/app/views/layouts/_beta_message.html.erb
<div id="dgu-beta__banner" class="dgu-beta__banner--hidden">
  <div class="dgu-beta__message">
    <p>
      We’ve been improving data.gov.uk to help you find and use open government data.<br />
      <%= link_to "Discover what’s changed", about_path %> and <%= link_to "get in touch", "http://www.smartsurvey.co.uk/s/3SEXD/" %> to give us your feedback.
    </p>

    <p>
      <a class="survey-close-button" href="#user-survey-cancel" id="dgu-survey-cancel" role="button">
        Don't show this message again
      </a>
    </p>

  </div>
</div>

datagovuk_find/app/views/layouts/_feedback_survey_banner.html.erb
<div id="dgu-phase-banner" class="phase-banner">
  <p>
    <strong class="phase-tag">BETA</strong>
    <span><%= t(".beta_survey_message_html", :href => link_to(t('.href'), t('.survey_url')))%>
    </span>
  </p>
</div>

datagovuk_find/app/views/layouts/_proposition_header.html.erb
<div class="header-proposition">
  <div class="content">
    <a href="#proposition-links" class="js-header-toggle menu"><%= t('.menu') %></a>
    <nav id="proposition-menu">
      <ul id="proposition-links">
        <li><%= link_to t('.publishers'), publishers_path %></li>
        <li><a href='https://guidance.data.gov.uk/publish_and_manage_data/'>Documentation</a></li>
        <li><%= link_to t('.support'), support_path %></li>
      </ul>
    </nav>
  </div>
</div>

datagovuk_find/app/views/layouts/_staging_ribbon.html.erb
<div class="corner-ribbon top-right sticky rainbow">Staging</div>

<style>
    .corner-ribbon{
      width: 200px;
      background: #e43;
      position: absolute;
      top: 25px;
      left: -50px;
      text-align: center;
      line-height: 50px;
      letter-spacing: 1px;
      color: #eee;
      transform: rotate(-45deg);
      -webkit-transform: rotate(-45deg);
      background: #005EA5;
      font-weight:bold;
    }

    /* Custom styles */
    .corner-ribbon.sticky{
      position: fixed;
    }

    .corner-ribbon.shadow{
      box-shadow: 0 0 3px rgba(0,0,0,.3);
    }

    .corner-ribbon.top-right{
      top: 25px;
      right: -50px;
      left: auto;
      transform: rotate(45deg);
      -webkit-transform: rotate(45deg);
    }
</style>

datagovuk_find/app/views/layouts/application.html.erb
<% content_for :head do %>
  <%= stylesheet_link_tag 'application' %>
  <%= javascript_include_tag 'application' %>
  <%= render 'layouts/analytics' %>
  <%= csrf_meta_tags %>
<% end %>

<% content_for :page_title do %> - <%= t('.site_name')%><% end %>

<% content_for :homepage_url do %>
  <%= root_path %>
<% end %>

<% content_for :cookie_message do %>
  <p>
    data.gov.uk uses cookies to make the site simpler.
    <%= link_to 'Find out more about cookies', cookies_path %>
  </p>
<% end %>

<% content_for :global_header_text do %>
  <%= t('.data_gov_uk')%>
  <div class="vertical-separator">|</div>
  <%= t('.find_open_data') %>
<% end %>

<% content_for :logo_link_title do %><%= t('.go_to_home') %><% end %>

<% content_for :header_class do %>
  with-proposition
<% end %>

<% content_for :proposition_header do %>
  <%= render 'layouts/proposition_header' %>
<% end %>

<% content_for :after_header do %>
  <%= render 'layouts/beta_message' %>
  <%= render 'layouts/staging_ribbon' if Rails.env.staging? %>
<% end %>

<% content_for :content do %>
  <div class="dgu-top-non-content">
    <div class="dgu-top-non-content__inner">
      <%= render 'layouts/feedback_survey_banner' %>
      <%= yield :breadcrumb %>
    </div>
  </div>

  <%= yield %>

  <div id="global-app-error" class="app-error hidden"></div>

  <%= javascript_tag do %>
    if (typeof window.GOVUK === 'undefined') document.body.className = document.body.className.replace('js-enabled', '');
  <% end %>
<% end %>

<% content_for :footer_support_links do %>
  <ul>
    <li><%= link_to 'About', about_path %></li>
    <li><%= link_to 'Accessibility', accessibility_path %></li>
    <li><%= link_to 'Cookies', cookies_path %></li>
    <li><%= link_to 'Privacy', privacy_path %></li>
    <li><%= link_to 'Terms and conditions', terms_path %></li>
    <li><%= link_to 'Support', support_path %></li>
    <li>Built by the <%= link_to 'Government Digital Service', 'https://www.gov.uk/government/organisations/government-digital-service' %></li>
  </ul>
<% end %>

<%= render template: 'layouts/govuk_template' %>