datagovuk_find/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'pages#home'

  get "/sites/default/files/*organogram_path", to: redirect("https://s3-eu-west-1.amazonaws.com/datagovuk-#{Rails.env}-ckan-organogram/legacy/%{organogram_path}"), format: false

  if ENV["CKAN_REDIRECTION_URL"].present?
    get 'dataset/edit/:legacy_name', to: redirect(domain: ENV['CKAN_REDIRECTION_URL'], subdomain: '', path: "/dataset/edit/%{legacy_name}")
  end

  get 'dataset/:uuid', to: 'datasets#show', uuid: /[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}/

  scope module: 'legacy' do
    get 'dataset/:legacy_name',
        to: 'datasets#available_soon',
        constraints: ReferrerConstraint.new

    get 'dataset/:legacy_name',                                 to: 'datasets#redirect'
    get 'dataset/:legacy_dataset_name/resource/:datafile_uuid', to: 'datafiles#redirect'

    get 'data/search', to: 'search#redirect'
  end

  scope module: 'pages' do
    get 'about'
    get 'accessibility'
    get 'cookies'
    get 'dashboard'
    get 'privacy'
    get 'publishers'
    get 'site-changes', to: :site_changes
    get 'support'
    get 'terms'
  end

  match "404", to: "errors#not_found", via: :all
  match "500", to: "errors#internal_server_error", via: :all

  get 'search/', to: 'search#search'

  resources :tickets, only: %i[new create]
  get 'tickets/confirmation', to: 'tickets#confirmation'

  get 'data/map-preview', to: 'map_previews#show', as: 'map_preview'

  defaults format: :xml do
    get 'data/preview_proxy', to: 'map_previews#proxy'
    get 'data/preview_getinfo', to: 'map_previews#getinfo'
  end

  get 'dataset/:uuid/:name', to: 'datasets#show', as: 'dataset'
  get 'dataset/:dataset_uuid/:name/datafile/:datafile_uuid/preview', to: 'previews#show', as: 'datafile_preview'

  get 'acknowledge', to: 'messages#acknowledge'

  # Route everything else to CKAN
  if ENV["CKAN_REDIRECTION_URL"].present?
    match '*path',
      to: redirect(domain: ENV['CKAN_REDIRECTION_URL'], subdomain: '', path: "/%{path}"),
      via: :all,
      constraints: { path: /(?!#{Regexp.quote(Rails.application.config.assets.prefix[1..-1])}).+/ }
  end
end

datagovuk_find/app/controllers/previews_controller.rb
class PreviewsController < ApplicationController
  def show
    append_content_security_policy_directives(
      connect_src: %w(s3-eu-west-1.amazonaws.com),
    )

    @dataset = Dataset.get_by_uuid(uuid: params[:dataset_uuid])
    @datafile = @dataset.datafiles.find { |f| f.uuid == params[:datafile_uuid] }

    raise Datafile::DatafileNotFound if @datafile.nil?
  end
end

datagovuk_find/app/helpers/previews_helper.rb
module PreviewsHelper
  def download_text(dataset, datafile)
    if datafile.csv? && dataset.organogram?
      "Download the CSV"
    else
      t('.download_file')
    end
  end
end

datagovuk_find/app/views/previews/show.html.erb
<% content_for :page_title do %><%= @datafile.name %><% end %>

<main role="main" id="content">
  <div class="grid-row">
    <div class="column-two-thirds">
      <%= link_to t('.back_link'), dataset_path(@dataset.uuid, @dataset.name), class: 'link-back' %>
      <h1 class="heading-large">
        <%= @dataset.title %>
        <span class="heading-secondary dgu-home-spacer__bottom"><%= @datafile.name %></span>
      </h1>

      <% if @datafile.csv? && @datafile.preview.exists? %>
        <p>You're previewing the first <%= @datafile.preview.line_count %> rows of this file.</p>
        <%= link_to download_text(@dataset, @datafile), @datafile.url,
          class: "button",
          data: {
            "ga-event" => "preview-download",
            "ga-format" => "CSV",
            "ga-publisher" => @dataset.organisation.name,
          }
        %>

        <% if @dataset.organogram? %>
          <%= link_to "View the full organogram", "#organogram", class: "button" %>
        <% end %>
    </div>
    <div class = 'column-full'>
      <section class="dgu-datafile-preview">
        <div class="dgu-datafile-preview__inner">
          <table>
            <thead>
              <tr>
                <% @datafile.preview.headers.each do |col| %>
                  <th><%= col %></th>
                <% end %>
              </tr>
            </thead>
            <tbody>
              <% @datafile.preview.rows.each do |row| %>
                <tr>
                  <% row.each do |col| %>
                    <td><%= col %></td>
                  <% end %>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
        <% else %>
          <p><%= "#{t('.no_preview_avail')} \"#{@datafile.name}\"" %></p>
        <% end %>
      </section>

      <% if @dataset.organogram? %>
        <section id="organogram" data-csv-url="<%= @datafile.url %>">
        </section>
      <% end %>
    </div>
  </div>
</main>